# Generated by Django 3.2.15 on 2022-09-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220909_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('applydate', models.DateField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.seekeruser')),
            ],
        ),
    ]
