# Generated by Django 3.2.15 on 2022-09-28 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.seekeruser')),
            ],
        ),
    ]
